version: "2"
services: 
  mongo:
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
    links:
      - mongo